In [1]:
import pandas as pd

dnkn = pd.read_csv("BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv")

dnkn

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Soft Serve,OREO Mix-In,510,21,11,0.5,55,350,70,2,55,14,562
776,Soft Serve,Soft Serve Cone,260,9,6,0,35,160,35,1,27,9,284
777,Soft Serve,Strawberry Coolatta Float,420,12,8,0,50,210,68,1,64,11,481
778,Hash Browns,Hash Browns,130,6,1,0,0,420,12,2,0,5,126
779,Dunkin’ Bowls,Egg White Bowl,250,11,4,0,15,490,20,0,3,14,243

In [2]:
dnkn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    object
 1   Item                 780 non-null    object
 2   Calories             780 non-null    object
 3   Total Fat (g)        780 non-null    object
 4   Saturated Fat (g)    780 non-null    object
 5   Trans Fat (g)        780 non-null    object
 6   Cholesterol (mg)     780 non-null    object
 7   Sodium (mg)          780 non-null    object
 8   Carbs (g)            780 non-null    object
 9   Fiber (g)            780 non-null    object
 10  Sugars (g)           780 non-null    object
 11  Protein (g)          780 non-null    object
 12  Weight Watcher Pnts  780 non-null    object
dtypes: object(13)
memory usage: 79.3+ KB

In [3]:
dnkn.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [4]:
dnkn.duplicated().sum()

1

In [5]:
dnkn[dnkn.duplicated(keep=False)]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
737,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275
760,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275

In [6]:
dnkn.nunique()

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

In [7]:
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Macchiato        42
Iced Cappuccino       42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

In [8]:
dnkn.describe(include='all')

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,780,780,780,780,780,780,780,780,780,780,780,780,780
unique,23,779,87,50,29,5,37,112,120,9,122,32,362
top,Hot Coffee,Ham and Cheese Rollups,170,0,0,0,0,180,35,0,0,4,5
freq,88,2,38,242,269,755,222,24,30,508,33,94,13

In [9]:
columns_to_check = [
    'Total Fat (g)',
    'Saturated Fat (g)',
    'Trans Fat (g)',
    'Cholesterol (mg)',
    'Sodium (mg)',
    'Fiber (g)',
    'Protein (g)',
    'Carbs (g)',
    'Sugars (g)'
]

for column in columns_to_check:
    print(f"\n{column}:")
    print(dnkn[column].unique())

Total Fat (g):
['0' '12' '9' '6' '4.5' '3' '10' '11' '28' '30' '22' '21' '23' '14' '15'
 '20' '19' '16' '18' '25' '31' '27' '17' '37' '40' '5' '8' '35' '26' '13'
 '7' '\xa0' '4' '1' '0.5' '1.5' '2.5' '2' '3.5' '42' '33' '24' '36' '54'
 '29' '32' '34' '52' '41' '43']

Saturated Fat (g):
['0' '6' '4.5' '3' '3.5' '2.5' '1.5' '4' '12' '14' '9' '10' '11' '7' '5'
 '8' '13' '18' '22' '17' '15' '\xa0' '0.5' '19' '21' '1' '2' '20' '16']

Trans Fat (g):
['0' '1.5' '1' '0.5' '\xa0']

Cholesterol (mg):
['0' '35' '25' '20' '15' '10' '50' '30' '40' '130' '100' '70' '105' '80'
 '55' '<5' '\xa0' '125' '45' '60' '185' '340' '180' '95' '65' '190' '360'
 '195' '265' '175' '220' '120' '200' '240' '205' '110' '115']

Sodium (mg):
['20' '15' '10' '65' '45' '30' '5' '60' '320' '240' '160' '300' '310'
 '470' '450' '420' '150' '340' '290' '400' '390' '440' '280' '135' '380'
 '480' '270' '430' '460' '360' '200' '370' '190' '330' '250' '170' '220'
 '180' '130' '230' '125' '100' '115' '75' '350' '260' '120' '\xa0' '95'
 '70' '50' '25' '85' '55' '90' '140' '105' '110' '210' '510' '570' '630'
 '500' '750' '620' '80' '40' '35' '1020' '810' '1260' '1460' '600' '410'
 '840' '1060' '800' '820' '1170' '520' '540' '670' '640' '1200' '590'
 '1190' '1210' '1080' '1240' '1980' '1010' '650' '960' '1140' '1220'
 '1270' '900' '910' '1050' '980' '1500' '1120' '710' '550' '850' '490'
 '760' '970' '580' '1160' '700' '680']

Fiber (g):
['0' '1' '2' '3' '4' '\xa0' '6' '5' '8']

Protein (g):
['1' '0' '2' '10' '7' '5' '4' '6' '3' '8' '11' '9' '\xa0' '12' '16' '15'
 '14' '13' '27' '24' '37' '17' '19' '26' '21' '23' '18' '28' '33' '22'
 '25' '20']

Carbs (g):
['0' '2' '1' '37' '27' '18' '112' '84' '56' '172' '129' '86' '113' '85'
 '31' '44' '57' '47' '63' '39' '55' '48' '36' '58' '33' '41' '34' '50'
 '40' '21' '42' '61' '43' '32' '52' '38' '59' '35' '45' '30' '49' '24'
 '176' '135' '95' '175' '134' '94' '180' '139' '97' '184' '142' '99' '141'
 '138' '183' '117' '88' '177' '160' '120' '80' '\xa0' '191' '147' '103'
 '195' '150' '105' '111' '83' '110' '13' '10' '7' '65' '64' '73' '70' '53'
 '71' '51' '87' '72' '66' '89' '82' '12' '9' '6' '26' '67' '5' '4' '46'
 '3' '28' '19' '17' '25' '23' '16' '15' '79' '78' '60' '11' '20' '54' '14'
 '69' '22' '75' '77' '29' '74' '68' '8' '92']

Sugars (g):
['0' '2' '1' '36' '27' '18' '110' '83' '55' '167' '125' '107' '80' '53'
 '10' '22' '24' '21' '11' '34' '32' '26' '14' '33' '20' '13' '15' '19'
 '16' '28' '17' '23' '12' '25' '5' '29' '165' '126' '88' '162' '124' '87'
 '158' '121' '84' '172' '132' '92' '176' '135' '94' '175' '134' '169'
 '130' '91' '173' '133' '93' '108' '81' '54' '112' '56' '111' '159' '119'
 '151' '113' '75' '\xa0' '181' '139' '97' '185' '142' '99' '98' '109' '82'
 '9' '6' '47' '35' '46' '63' '31' '61' '30' '60' '45' '58' '43' '57' '38'
 '62' '50' '39' '70' '42' '71' '65' '69' '64' '51' '66' '40' '49' '37' '7'
 '3' '4' '59' '48' '74' '52' '68' '67' '78' '8' '44' '85']

In [10]:
dnkn1 = dnkn.copy()
dnkn1

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Soft Serve,OREO Mix-In,510,21,11,0.5,55,350,70,2,55,14,562
776,Soft Serve,Soft Serve Cone,260,9,6,0,35,160,35,1,27,9,284
777,Soft Serve,Strawberry Coolatta Float,420,12,8,0,50,210,68,1,64,11,481
778,Hash Browns,Hash Browns,130,6,1,0,0,420,12,2,0,5,126
779,Dunkin’ Bowls,Egg White Bowl,250,11,4,0,15,490,20,0,3,14,243

In [11]:
food_categories = [
    'Donuts', 'Sandwiches', 'Muffins', 'Kolache',
    'Soft Serve', 'Hash Browns', 'Dunkin’ Bowls'
]

dnkn2 = dnkn1[~dnkn1['Category'].isin(food_categories)].copy()

dnkn2['Category'].value_counts()

Category
Hot Coffee            88
Hot Latte             63
Iced Latte            63
Iced Coffee           63
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Dunkin’ Refreshers     9
Coolatta               9
Hot Americano          3
Iced Americano         3
Name: count, dtype: int64

In [12]:
dnkn2 = dnkn2.drop_duplicates()

print("Duplicate rows remaining:", dnkn2.duplicated().sum())
print("Total rows:", len(dnkn2))
dnkn2

Duplicate rows remaining: 0
Total rows: 594

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Medium",130,0,0,0,0,15,29,0,27,1,156
677,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Small",80,0,0,0,0,10,19,0,18,0,98
678,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Large",900,17,13,0,40,570,175,1,162,12,1063
679,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Medium",700,14,10,0,30,430,134,1,124,9,825
680,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Small",500,11,8,0,25,290,95,1,87,6,589

In [13]:
dnkn2 = dnkn2.replace('\xa0', '')
dnkn2 = dnkn2.replace('<5', '')

dnkn2

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Medium",130,0,0,0,0,15,29,0,27,1,156
677,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Small",80,0,0,0,0,10,19,0,18,0,98
678,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Large",900,17,13,0,40,570,175,1,162,12,1063
679,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Medium",700,14,10,0,30,430,134,1,124,9,825
680,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Small",500,11,8,0,25,290,95,1,87,6,589

In [14]:
print("Non-breaking spaces remaining:", (dnkn2 == '\xa0').sum().sum())
print("<5 values remaining:", (dnkn2 == '<5').sum().sum())

Non-breaking spaces remaining: 0
<5 values remaining: 0

In [15]:
import numpy as np

dnkn2 = dnkn2.replace('', np.nan)

dnkn2.isnull().sum()

Category                 0
Item                     0
Calories                 3
Total Fat (g)            3
Saturated Fat (g)        3
Trans Fat (g)            3
Cholesterol (mg)       137
Sodium (mg)              3
Carbs (g)                3
Fiber (g)                3
Sugars (g)               3
Protein (g)              3
Weight Watcher Pnts      3
dtype: int64

In [16]:
print("Missing values by column:")
print(dnkn2.isnull().sum())

print("Total rows with missing values:", dnkn2.isnull().any(axis=1).sum())

Missing values by column:
Category                 0
Item                     0
Calories                 3
Total Fat (g)            3
Saturated Fat (g)        3
Trans Fat (g)            3
Cholesterol (mg)       137
Sodium (mg)              3
Carbs (g)                3
Fiber (g)                3
Sugars (g)               3
Protein (g)              3
Weight Watcher Pnts      3
dtype: int64
Total rows with missing values: 137

In [17]:
print(dnkn['Cholesterol (mg)'].value_counts().head(15))

Cholesterol (mg)
0      222
<5     140
20     100
10      53
25      49
30      40
35      33
40      25
15      21
45      11
60       8
55       8
50       7
70       7
100      6
Name: count, dtype: int64

In [18]:
dnkn3 = dnkn2.dropna().copy()

print("Final dataset shape:", dnkn3.shape)
dnkn3

Final dataset shape: (457, 13)

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Medium",130,0,0,0,0,15,29,0,27,1,156
677,Dunkin’ Refreshers,"Strawberry Dragonfruit Dunkin’ Refreshers, Small",80,0,0,0,0,10,19,0,18,0,98
678,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Large",900,17,13,0,40,570,175,1,162,12,1063
679,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Medium",700,14,10,0,30,430,134,1,124,9,825
680,Dunkin’ Refreshers,"Butter Pecan Swirl Frozen Chocolate, Small",500,11,8,0,25,290,95,1,87,6,589

In [19]:
print("Missing values remaining:", dnkn3.isnull().sum().sum())
print("Dataset shape:", dnkn3.shape)

Missing values remaining: 0
Dataset shape: (457, 13)

In [20]:
numeric_columns = dnkn3.columns.drop(['Category', 'Item'])

dnkn3[numeric_columns] = dnkn3[numeric_columns].apply(
    pd.to_numeric
)

dnkn3.dtypes

Category                object
Item                    object
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

In [21]:
print("Dataset shape:", dnkn3.shape)
print("Missing values:", dnkn3.isnull().sum().sum())
print("Duplicate rows:", dnkn3.duplicated().sum())
print("\nData types:")
print(dnkn3.dtypes)

Dataset shape: (457, 13)
Missing values: 0
Duplicate rows: 0

Data types:
Category                object
Item                    object
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

In [22]:
dnkn3.to_csv("BUS303_Dunkin_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [23]:
dnkn4 = pd.read_csv("BUS303_Dunkin_Cleaned.csv")

print("Reloaded dataset shape:", dnkn4.shape)
print("Missing values:", dnkn4.isnull().sum().sum())
print("Duplicate rows:", dnkn4.duplicated().sum())

Reloaded dataset shape: (457, 13)
Missing values: 0
Duplicate rows: 0

For Deliverable Two, I worked with the Dunkin' Donuts nutritional dataset to identify and clean issues that could affect data analysis. I started by reviewing the dataset's structure, checking for missing values and duplicate records, and examining the different food and beverage categories. I also reviewed the nutritional columns to identify values that needed cleaning.

During the cleaning process, I removed selected food categories, eliminated duplicate records, and handled missing and nonnumeric values. I also converted the nutritional columns into numeric data types so they could be used for future analysis.

After completing the cleaning process, my final dataset contained 457 rows and 13 columns, with no missing values or duplicate records. I then saved the cleaned dataset as a CSV file and reloaded it to verify that the file was saved correctly. The cleaned dataset is now ready for further analysis.