In [1]:
import pandas as pd

In [2]:
sbux = pd.read_csv("BUS303_Signature_Term_Project_Starbucks_Beverage_Menu.csv")

In [3]:
sbux

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [4]:
sbux[sbux.isnull().all(axis=1)]

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sbux.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

In [6]:
sbux2 = sbux.dropna(how="all")

In [7]:
sbux2[sbux2.isnull().all(axis=1)]

Empty DataFrame
Columns: [Product_Name, Size, Milk, Whip, Serving_Size_ml, Calories, Total_Fat_g, Saturated_Fat_g, Trans_Fat_g, Cholesterol_mg, Sodium_mg, Carbohydrates_g, Dietary_Fiber_g, Sugar_g, Protein_g, Vitamin_A_%DV, Vitamin_C_%DV, Calcium_%DV, Iron_%DV, Caffiene_milligrams]
Index: []

In [8]:
sbux2.dtypes

Product_Name            object
Size                    object
Milk                    object
Whip                    object
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                 object
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [9]:
sbux2["Sugar_g"] = sbux2["Sugar_g"].astype(float)

ValueError: could not convert string to float: 'zero'

In [10]:
sbux2[sbux2["Sugar_g"] == "zero"]

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0

In [11]:
sbux2.loc[1, "Sugar_g"] = 0

In [12]:
sbux2.loc[1, "Sugar_g"]

0

In [13]:
sbux2["Sugar_g"] = sbux2["Sugar_g"].astype(float)

/tmp/ipykernel_381/3190073667.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sbux2["Sugar_g"] = sbux2["Sugar_g"].astype(float)

In [14]:
sbux2["Sugar_g"].dtype

dtype('float64')

In [15]:
sbux2[sbux2.isnull().any(axis=1)]

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
15,Brewed Coffee Traveler - Medium Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,NaN,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,155.0

In [16]:
sbux3 = sbux2.dropna()

In [17]:
sbux3[sbux3.isnull().any(axis=1)]

Empty DataFrame
Columns: [Product_Name, Size, Milk, Whip, Serving_Size_ml, Calories, Total_Fat_g, Saturated_Fat_g, Trans_Fat_g, Cholesterol_mg, Sodium_mg, Carbohydrates_g, Dietary_Fiber_g, Sugar_g, Protein_g, Vitamin_A_%DV, Vitamin_C_%DV, Calcium_%DV, Iron_%DV, Caffiene_milligrams]
Index: []

In [18]:
sbux3.columns

Index(['Product_Name', 'Size', 'Milk', 'Whip', 'Serving_Size_ml', 'Calories',
       'Total_Fat_g', 'Saturated_Fat_g', 'Trans_Fat_g', 'Cholesterol_mg',
       'Sodium_mg', 'Carbohydrates_g', 'Dietary_Fiber_g', 'Sugar_g',
       'Protein_g', 'Vitamin_A_%DV', 'Vitamin_C_%DV', 'Calcium_%DV',
       'Iron_%DV', 'Caffiene_milligrams'],
      dtype='object')

In [19]:
sbux3 = sbux3.rename(columns={"Caffiene_milligrams": "Caffeine_milligrams"})

In [20]:
sbux3.columns

Index(['Product_Name', 'Size', 'Milk', 'Whip', 'Serving_Size_ml', 'Calories',
       'Total_Fat_g', 'Saturated_Fat_g', 'Trans_Fat_g', 'Cholesterol_mg',
       'Sodium_mg', 'Carbohydrates_g', 'Dietary_Fiber_g', 'Sugar_g',
       'Protein_g', 'Vitamin_A_%DV', 'Vitamin_C_%DV', 'Calcium_%DV',
       'Iron_%DV', 'Caffeine_milligrams'],
      dtype='object')

In [21]:
sbux3.to_csv("Starbucks_Beverage_Menu_Cleaned.csv", index=False)

In [22]:
sbux_clean = pd.read_csv("Starbucks_Beverage_Menu_Cleaned.csv")

In [23]:
sbux_clean.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffeine_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [24]:
sbux_clean.shape == sbux3.shape

True